/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as BulletRunRouteImport } from './routes/bullet-run'
import { Route as ClassicRouteImport } from './routes/classic'
import { Route as PracticeRouteImport } from './routes/practice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const BulletRunRoute = BulletRunRouteImport.update({
  id: '/bullet-run',
  path: '/bullet-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicRoute = ClassicRouteImport.update({
  id: '/classic',
  path: '/classic',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/bullet-run': typeof BulletRunRoute
  '/classic': typeof ClassicRoute
  '/practice': typeof PracticeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/bullet-run': typeof BulletRunRoute
  '/classic': typeof ClassicRoute
  '/practice': typeof PracticeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeRoute
  '/bullet-run': typeof BulletRunRoute
  '/classic': typeof ClassicRoute
  '/practice': typeof PracticeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arcade' | '/bullet-run' | '/classic' | '/practice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arcade' | '/bullet-run' | '/classic' | '/practice'
  id: '__root__' | '/' | '/arcade' | '/bullet-run' | '/classic' | '/practice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcadeRoute: typeof ArcadeRoute
  BulletRunRoute: typeof BulletRunRoute
  ClassicRoute: typeof ClassicRoute
  PracticeRoute: typeof PracticeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bullet-run': {
      id: '/bullet-run'
      path: '/bullet-run'
      fullPath: '/bullet-run'
      preLoaderRoute: typeof BulletRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classic': {
      id: '/classic'
      path: '/classic'
      fullPath: '/classic'
      preLoaderRoute: typeof ClassicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcadeRoute: ArcadeRoute,
  BulletRunRoute: BulletRunRoute,
  ClassicRoute: ClassicRoute,
  PracticeRoute: PracticeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
